### PR TITLE
eslint: add eslint rules to js files

### PR DESCRIPTION
**Pull request by Samk13**
:heart: Thank you for your contribution!

### Description

This PR 
- Implements JS linting.
- add --fix option to the linting script for auto fix
- apply the auto fix command to the package (no manual fixes)

### Checklist

Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:

- [x] I'm aware of the [code of conduct](https://inveniordm.docs.cern.ch/contribute/code-of-conduct/).
- [x] I've created [logical separate commits](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commits) and followed the [commit message format](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#commit-message).
- [x] I've added relevant test cases.
- [x] I've added relevant documentation.
- [x] I've marked [translation strings](https://inveniordm.docs.cern.ch/develop/best-practices/i18n/) (for relevant code).
- [x] I've followed the [CSS/JS](https://inveniordm.docs.cern.ch/develop/best-practices/css-js/) and [React](https://inveniordm.docs.cern.ch/develop/best-practices/react/) guidelines (for relevant code).
- [x] I've followed the [web accessibility](https://inveniordm.docs.cern.ch/develop/best-practices/accessibility/) guidelines (for relevant code).
- [x] I've followed the [user interface](https://inveniordm.docs.cern.ch/develop/best-practices/ui/) guidelines (for relevant code).
- [x] I've identified the [copyright holder(s)](https://inveniordm.docs.cern.ch/contribute/copyright-policy/) and updated copyright headers for touched files (>15 lines contributions).
- [x] I've NOT included third-party code (copy/pasted source code or new dependencies).

**Third-party code**

If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).

**Reminder**

By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:

1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license your contribution under the current repository’s license.

### CODE REVIEW

**Review by tmorrell — APPROVED** [review]
Looks great! Couple of additional thoughts:
- Would it be good to add this to the CI, like in https://github.com/inveniosoftware/invenio-communities/blob/554a1b9860ff0e0646e236a961e0310dc51bca1b/.github/workflows/tests.yml#L51
- How about adding the eslint commit to [.git-blame-ignore-revs](https://github.com/inveniosoftware/invenio-queues/pull/25/commits/9ec5c38e46eee0e51b53ffbccd94d9cfe3a1d1f9#diff-f247fbfbe928b907db42554d0b3006b28dd11c25a59be031abda73b11a2c934a)

**Comment by fenekku** [comment]
Coordination:

Bumping to attention of @kpsherva or even @zzacharo : adding eslint rules is something you are probably more familiar with.

**Comment by kpsherva** [comment]
LGTM, thank you for adding this. It only needs a rebase

**Review by kpsherva — APPROVED** [review]

**Comment by chokribr** [comment]
@kpsherva  @tmorrell does this  an aproved PR?

**Comment by Samk13** [comment]
Done, code rebased and pushed. Please review. Thanks! @kpsherva @tmorrell  @chokribr

**Comment by tmorrell** [comment]
Yup, I think this can go to approved.

**Pull request merged**
